repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0 # Use the mirror which supports additional_dependencies
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # Target .js, .ts, .jsx, .tsx files
        types: [file]
        args: [--fix, --config, ha-raumkernel-addon/rootfs/app/eslint.config.js]
        additional_dependencies:
          - eslint@9.17.0
          - globals@15.14.0
          - "@eslint/js@9.17.0"
