# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Raumkernel: Addon for Raumfeld devices"
version: "1.2.12"
slug: ha-raumkernel-addon
description: "Home Assistant Add-on for Teufel Raumfeld devices, providing a WebSocket API for the Raumfeld integration."
url: "https://github.com/ulilicht/ha-raumkernel"
arch:
  - aarch64
  - amd64
init: false
host_network: true
homeassistant_api: true
map:
  - share:rw
  - homeassistant_config:rw
options:
  LOG_LEVEL: 2
  PORT: 3000
  RAUMFELD_HOST: ""
  ENABLE_AUTO_INSTALL: true
  DEVELOPER_MODE: false
schema:
  LOG_LEVEL: int
  PORT: int
  RAUMFELD_HOST: str?
  ENABLE_AUTO_INSTALL: bool
  DEVELOPER_MODE: bool
