# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Teufel Raumfeld (Raumkernel Addon)"
version: "1.2.0"
slug: ha-raumkernel-addon
description: "Home Assistant Add-on for Teufel Raumfeld devices, providing a WebSocket API for the Raumfeld integration."
url: "https://github.com/ulilicht/ha-raumkernel"
arch:
  - aarch64
  - amd64
init: false
host_network: true
map:
  - share:rw
options:
  LOG_LEVEL: 2
  PORT: 3000
schema:
  LOG_LEVEL: int
  PORT: int
